version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.8
       environment: 
            PIPENV_VENV_IN_PROJECT: true
            DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
     - image: circleci/postgres:9.6.2
       environment: 
         POSTGRES_USER: root
         POSTGRES_DB: song_search
    steps:
      - checkout
      # - restore_cache:
      #       key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install pipenv
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - "venv"