# Generated by Django 3.2.3 on 2021-05-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_albumartist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumArtist',
        ),
    ]
